In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
train=pd.read_csv('/content/car_price_train.csv')
test=pd.read_csv('/content/carprice_test.csv')

In [2]:
train

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,Ford,F-150 Lariat,2018,74349,Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Blue,Gray,None reported,Yes,11000
1,1,BMW,335 i,2007,80000,Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,Black,Black,None reported,Yes,8250
2,2,Jaguar,XF Luxury,2009,91491,Gasoline,300.0HP 4.2L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Purple,Beige,None reported,Yes,15000
3,3,BMW,X7 xDrive40i,2022,2437,Hybrid,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Brown,None reported,Yes,63500
4,4,Pontiac,Firebird Base,2001,111000,Gasoline,200.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,7850
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54268,54268,BMW,X6 xDrive50i,2017,29000,Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Brown,None reported,Yes,29000
54269,54269,Audi,A4 2.0T Premium,2015,94634,E85 Flex Fuel,220.0HP 2.0L 4 Cylinder Engine Flex Fuel Capab...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,6500
54270,54270,Porsche,Cayenne S,2013,40989,Gasoline,420.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,At least 1 accident or damage reported,Yes,18950
54271,54271,Porsche,911 Carrera 4 GTS,2023,1518,Gasoline,4.0L H6 24V GDI DOHC,8-Speed Automatic with Auto-Shift,Beige,Brown,None reported,Yes,194965
54272,54272,Audi,A5 Sportback S line Premium Plus,2021,35000,Hybrid,261.0HP 2.0L 4 Cylinder Engine Gasoline/Mild E...,8-Speed A/T,Black,Black,None reported,Yes,37499

In [3]:
test

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,54273,Mercedes-Benz,E-Class E 350,2014,73000,Gasoline,302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,Beige,None reported,Yes
1,54274,Lexus,RX 350 Base,2015,128032,Gasoline,275.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,None reported,Yes
2,54275,Mercedes-Benz,C-Class C 300,2015,51983,Gasoline,241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Blue,White,None reported,Yes
3,54276,Land,Rover Range Rover 5.0L Supercharged Autobiogra...,2018,29500,Gasoline,518.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,White,At least 1 accident or damage reported,Yes
4,54277,BMW,X6 xDrive40i,2020,90000,Gasoline,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
36178,90451,GMC,Yukon Denali,2019,4500,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,10-Speed A/T,Gray,Black,None reported,Yes
36179,90452,Chevrolet,Silverado 1500 Z71 Extended Cab,2004,185000,Gasoline,295.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,4-Speed A/T,Red,Gray,At least 1 accident or damage reported,Yes
36180,90453,Toyota,Corolla LE,2011,116000,Gasoline,132.0HP 1.8L 4 Cylinder Engine Gasoline Fuel,5-Speed M/T,Beige,Gray,None reported,Yes
36181,90454,Lincoln,Navigator Reserve,2019,39000,Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Orange,None reported,Yes
36182,90455,Chevrolet,Tahoe LT,2012,162731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Black,Black,At least 1 accident or damage reported,Yes

In [4]:
#first 3 rows
print(train.head(3))

   id   brand         model  model_year  milage fuel_type  \
0   0    Ford  F-150 Lariat        2018   74349  Gasoline
1   1     BMW         335 i        2007   80000  Gasoline
2   2  Jaguar     XF Luxury        2009   91491  Gasoline

                                              engine  transmission ext_col  \
0      375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel  10-Speed A/T    Blue
1  300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...   6-Speed M/T   Black
2       300.0HP 4.2L 8 Cylinder Engine Gasoline Fuel   6-Speed A/T  Purple

  int_col       accident clean_title  price
0    Gray  None reported         Yes  11000
1   Black  None reported         Yes   8250
2   Beige  None reported         Yes  15000

In [5]:
#last 3 rows
print(train.tail(3))

          id    brand                             model  model_year  milage  \
54270  54270  Porsche                         Cayenne S        2013   40989
54271  54271  Porsche                 911 Carrera 4 GTS        2023    1518
54272  54272     Audi  A5 Sportback S line Premium Plus        2021   35000

      fuel_type                                             engine  \
54270  Gasoline      420.0HP 3.6L V6 Cylinder Engine Gasoline Fuel
54271  Gasoline                               4.0L H6 24V GDI DOHC
54272    Hybrid  261.0HP 2.0L 4 Cylinder Engine Gasoline/Mild E...

                            transmission ext_col int_col  \
54270     Transmission w/Dual Shift Mode   White   Black
54271  8-Speed Automatic with Auto-Shift   Beige   Brown
54272                        8-Speed A/T   Black   Black

                                     accident clean_title   price
54270  At least 1 accident or damage reported         Yes   18950
54271                           None reported         Yes  194965
54272                           None reported         Yes   37499

In [6]:
#number of rows amd columns in training data
print(train.shape)
#no of rows and columns in testing data
print(test.shape)

(54273, 13)
(36183, 12)

In [7]:
#statistical summary of training data
print(train.describe())

                 id    model_year         milage         price
count  54273.000000  54273.000000   54273.000000  5.427300e+04
mean   27136.000000   2015.091979   72746.175667  3.921844e+04
std    15667.409917      5.588909   50469.490448  7.282634e+04
min        0.000000   1974.000000     100.000000  2.000000e+03
25%    13568.000000   2012.000000   32268.000000  1.550000e+04
50%    27136.000000   2016.000000   66107.000000  2.800000e+04
75%    40704.000000   2019.000000  102000.000000  4.500000e+04
max    54272.000000   2024.000000  405000.000000  2.954083e+06

In [8]:
#informations
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54273 entries, 0 to 54272
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            54273 non-null  int64
 1   brand         54273 non-null  object
 2   model         54273 non-null  object
 3   model_year    54273 non-null  int64
 4   milage        54273 non-null  int64
 5   fuel_type     54273 non-null  object
 6   engine        54273 non-null  object
 7   transmission  54273 non-null  object
 8   ext_col       54273 non-null  object
 9   int_col       54273 non-null  object
 10  accident      54273 non-null  object
 11  clean_title   54273 non-null  object
 12  price         54273 non-null  int64
dtypes: int64(4), object(9)
memory usage: 5.4+ MB
None

In [9]:
#column names in train data
print(train.columns)
#column names in test data
print(test.columns)

Index(['id', 'brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title',
       'price'],
      dtype='object')
Index(['id', 'brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title'],
      dtype='object')

In [10]:
#datatypes in train
print(train.dtypes)
#datatypes in test
print(test.dtypes)

id               int64
brand           object
model           object
model_year       int64
milage           int64
fuel_type       object
engine          object
transmission    object
ext_col         object
int_col         object
accident        object
clean_title     object
price            int64
dtype: object
id               int64
brand           object
model           object
model_year       int64
milage           int64
fuel_type       object
engine          object
transmission    object
ext_col         object
int_col         object
accident        object
clean_title     object
dtype: object

In [11]:
#DATA CLEANING

#duplicates
print("Train duplicates:", train.duplicated().sum())
print("Test duplicates:", test.duplicated().sum())

Train duplicates: 0
Test duplicates: 0

In [12]:
#handling unusual values
for col in train.select_dtypes(include='object').columns:
    train[col] = train[col].replace(['–', 'not supported'], np.nan)

for col in test.select_dtypes(include='object').columns:
    test[col] = test[col].replace(['–', 'not supported'], np.nan)

In [13]:
#Dropping unwanted columns
train.drop(['id', 'clean_title'], axis=1, inplace=True)
test.drop(['id', 'clean_title'], axis=1, inplace=True)

In [14]:
#null values
print(train.isnull().sum())
print(test.isnull().sum())

brand              0
model              0
model_year         0
milage             0
fuel_type        298
engine           335
transmission       7
ext_col           41
int_col         1045
accident           0
price              0
dtype: int64
brand             0
model             0
model_year        0
milage            0
fuel_type       201
engine          227
transmission      3
ext_col          27
int_col         704
accident          0
dtype: int64

In [15]:
#null value handling in training dataset
train_obj=train.select_dtypes(include=object).columns
train_num=train.select_dtypes(exclude=object).columns
for ch in train_obj:
  train[ch]=train[ch].fillna(train[ch].mode()[0])
for i in train_num:
  train[i]=train[i].fillna(train[i].median())

In [16]:
#null value handling in testing dataset
test_obj=test.select_dtypes(include=object).columns
test_num=test.select_dtypes(exclude=object).columns
for ch in test_obj:
  test[ch]=test[ch].fillna(train[ch].mode()[0])
for i in test_num:
  test[i]=test[i].fillna(test[i].median())

In [17]:
#LABEL ENCODING FOR MODEL,ENGINE COLUMN
list1=['model','engine']
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in list1:
  train[i]=le.fit_transform(train[i])
  test[i]=le.fit_transform(test[i])

In [18]:
#ONE-HOT ENCODING FOR REMAINING COLUMNS
train = pd.get_dummies(train, drop_first=True)
test = pd.get_dummies(test, drop_first=True)

In [19]:
train

,model,model_year,milage,engine,price,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,...,int_col_Titan Black,int_col_Titan Black / Quarzit,int_col_Tupelo,int_col_Very Light Cashmere,int_col_Walnut,int_col_Whisper Beige,int_col_White,int_col_White / Brown,int_col_Yellow,accident_None reported
0,644,2018,74349,719,11000,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,49,2007,80000,534,8250,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
2,1771,2009,91491,541,15000,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,1748,2022,2437,646,63500,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
4,693,2001,111000,219,7850,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54268,1745,2017,29000,856,29000,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
54269,165,2015,94634,266,6500,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
54270,421,2013,40989,817,18950,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54271,142,2023,1518,762,194965,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
54272,176,2021,35000,372,37499,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True

In [20]:
test

,model,model_year,milage,engine,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,...,int_col_Sport,int_col_Tan,int_col_Titan Black / Quarzit,int_col_Tupelo,int_col_Very Light Cashmere,int_col_Walnut,int_col_White,int_col_White / Brown,int_col_Yellow,accident_None reported
0,528,2014,73000,544,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,1246,2015,128032,410,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,317,2015,51983,311,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,1318,2018,29500,911,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,1710,2020,90000,633,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36178,1763,2019,4500,807,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
36179,1481,2004,185000,473,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
36180,480,2011,116000,30,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
36181,1082,2019,39000,843,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
36182,1575,2012,162731,601,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [21]:
#FEATURE AND TARGET SEPARATIONS
# Separate target
ytrain= train['price']
xtrain = train.drop('price',axis=1)
xtest = test
print(ytrain.shape)
print(xtrain.shape)
print(xtest.shape)

(54273,)
(54273, 485)
(36183, 440)

In [22]:
# Align train and test columns
xtrain, xtest = xtrain.align(xtest,join='left',axis=1,fill_value=0)

In [23]:
#FEATURE SCALING
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(xtrain)
xtrain=scaler.transform(xtrain)
xtrain

array([[-0.45473117,  0.52032471,  0.03175858, ..., -0.02013759,
        -0.01135756,  0.60030154],
       [-1.55278622, -1.44787727,  0.14372824, ..., -0.02013759,
        -0.01135756,  0.60030154],
       [ 1.62511427, -1.09002236,  0.37141245, ..., -0.02013759,
        -0.01135756,  0.60030154],
       ...,
       [-0.86627113, -0.37431255, -0.62924091, ..., -0.02013759,
        -0.01135756, -1.66582947],
       [-1.38115745,  1.41496198, -1.41132457, ..., -0.02013759,
        -0.01135756,  0.60030154],
       [-1.31841144,  1.05710707, -0.74790776, ..., -0.02013759,
        -0.01135756,  0.60030154]])

In [24]:
xtest=scaler.transform(xtest)
xtest

array([[-0.66880577, -0.1953851 ,  0.00502931, ..., -0.02013759,
        -0.01135756,  0.60030154],
       [ 0.65624217, -0.01645765,  1.09544069, ..., -0.02013759,
        -0.01135756,  0.60030154],
       [-1.05820008, -0.01645765, -0.41140433, ..., -0.02013759,
        -0.01135756,  0.60030154],
       ...,
       [-0.75738836, -0.73216746,  0.85703704, ..., -0.02013759,
        -0.01135756,  0.60030154],
       [ 0.35358498,  0.69925217, -0.66865122, ..., -0.02013759,
        -0.01135756,  0.60030154],
       [ 1.26340202, -0.55324001,  1.78297131, ..., -0.02013759,
        -0.01135756, -1.66582947]])

In [25]:
from sklearn.model_selection import GridSearchCV
#HYPERPARAMETER TUNING FOR Linear Regression
from sklearn.linear_model import LinearRegression
lr_model=LinearRegression()
lr_param={'fit_intercept':[True,False],'positive':[True,False]}
lr_grid=GridSearchCV(lr_model,lr_param,cv=3,scoring='r2')
lr_grid.fit(xtrain,ytrain)
lr_grid.best_params_

{'fit_intercept': True, 'positive': False}

In [26]:
#LR MODEL BUILDING
lr=LinearRegression(fit_intercept=True, positive= False)
lr.fit(xtrain,ytrain)
lr_ypred=lr.predict(xtest)
lr_ypred

array([37549.69254783, 23286.35115869, 40690.63447126, ...,
       18128.45167234, 66439.7985523 , 14880.84826424])

In [ ]:
#HYPERPARAMETER TUNING FOR KNN
from sklearn.neighbors import KNeighborsRegressor
knn_model=KNeighborsRegressor()
knn_param={'n_neighbors':[5,7,9,11],'weights':['distance','random'],'metric':['euclidean','manhattan']}
knn_grid=GridSearchCV(knn_model,knn_param,cv=3,scoring='r2')
knn_grid.fit(xtrain,ytrain)
knn_grid.best_params_

In [ ]:
#KNN MODEL BUILDING
knn=KNeighborsRegressor(metric= 'euclidean', n_neighbors=5, weights='distance')
knn.fit(xtrain,ytrain)
knn_ypred=knn.predict(xtest)
knn_ypred

In [ ]:
#HYPERPARAMETER TUNING FOR DT
from sklearn.tree import DecisionTreeRegressor
dt_model=DecisionTreeRegressor(random_state=41)
dt_param={'criterion':['squared_error','friedman_mse','absolute_error'],'max_depth':[5,7,10,None],
          'min_samples_split':[2,5,10],'min_samples_leaf':[1,2,4]}
dt_grid=GridSearchCV(dt_model,dt_param,cv=3,scoring='r2')
dt_grid.fit(xtrain,ytrain)
dt_grid.best_params_

In [ ]:
#DECISION TREE REGRESSION MODEL BUILDING
dt=DecisionTreeRegressor(criterion= 'squared_error',max_depth= 7,min_samples_leaf= 1,min_samples_split=2,random_state=41)
dt.fit(xtrain,ytrain)
dt_ypred=dt.predict(xtest)
dt_ypred

In [ ]:
#HYPERPARAMETER TUNING OF RANDOM FOREST
from sklearn.ensemble import RandomForestRegressor
rfr_model=RandomForestRegressor(random_state=41)
rfr_param={'n_estimators':[30,50],'max_depth':[5,10],'min_samples_split':[2,5],'min_samples_leaf':[1,2]}
rfr_grid=GridSearchCV(rfr_model,rfr_param,cv=3,scoring='r2',)
rfr_grid.fit(xtrain,ytrain)
rfr_grid.best_params_

In [ ]:
#RANDOM FOREST REGRESSION MODEL BUILDING
rfr=RandomForestRegressor(n_estimators=50,max_depth=10,min_samples_split=2,min_samples_leaf=2)
rfr.fit(xtrain,ytrain)
rfr_ypred=rfr.predict(xtest)
rfr_ypred

In [ ]:
#HYPERPARAMETER TUNING OF XGBOOST
from xgboost import XGBRegressor
xgb_model=XGBRegressor(random_state=41)
xgb_param={'n_estimators':[100,200],'max_depth':[3,5,7,10],'learning_rate':[0.01,0.1],'subsample':[0.8,1.0]}
xgb_grid=GridSearchCV(xgb_model,xgb_param,cv=5,scoring='r2')
xgb_grid.fit(xtrain,ytrain)
xgb_grid.best_params_

In [ ]:
#XGBOOST REGRESSION MODEL BUILDING
xgb=XGBRegressor(learning_rate=0.1,max_depth= 7, n_estimators=200, subsample=0.8)
xgb.fit(xtrain,ytrain)
xgb_ypred=xgb.predict(xtest)
xgb_ypred

In [ ]:
#DIVIDING THE TRAIN DATASET TO TRAINING AND TESTING DATASET FOR EVALUATING THE PERFORMANCE OF MODEL
x1=train.drop('price',axis=1)
y1=train['price']
x1

In [ ]:
#TRAIN-TEST-SPLITTING
from sklearn.model_selection import train_test_split
x1train,x1test,y1train,y1test=train_test_split(x1,y1,test_size=0.30,random_state=41)
print(x1train.shape)
print(x1test.shape)
print(y1train.shape)
print(y1test.shape)

In [ ]:
#FEATURE SCALING
scale=StandardScaler()
scale.fit(x1train)
x1train=scale.transform(x1train)
x1train

In [ ]:
x1test=scale.transform(x1test)
x1test

In [ ]:
#LR MODEL BUILDING
lr1=LinearRegression(fit_intercept=True, positive= False)
lr1.fit(x1train,y1train)
lr1_ypred=lr1.predict(x1test)
lr1_ypred

In [ ]:
#KNN MODEL BUILDING
knn1=KNeighborsRegressor(metric= 'euclidean', n_neighbors=5, weights='distance')
knn1.fit(x1train,y1train)
knn1_ypred=knn1.predict(x1test)
knn1_ypred

In [ ]:
#DECISION TREE REGRESSION MODEL BUILDING
dt1=DecisionTreeRegressor(criterion= 'squared_error',max_depth= 7,min_samples_leaf= 1,min_samples_split=2,random_state=41)
dt1.fit(x1train,y1train)
dt1_ypred=dt1.predict(x1test)
dt1_ypred

In [ ]:
#RANDOM FOREST REGRESSION MODEL BUILDING
rfr1=RandomForestRegressor(n_estimators=50,max_depth=10,min_samples_split=2,min_samples_leaf=2)
rfr1.fit(x1train,y1train)
rfr1_ypred=rfr1.predict(x1test)
rfr1_ypred

In [ ]:
#XGBOOST REGRESSION MODEL BUILDING
xgb1=XGBRegressor(learning_rate=0.1,max_depth= 7, n_estimators=200, subsample=0.8)
xgb1.fit(x1train,y1train)
xgb1_ypred=xgb1.predict(x1test)
xgb1_ypred

In [ ]:
#TRAIN TEST SCORING
print("LR  Training Score:",lr1.score(x1train,y1train),  "Testing score:",lr1.score(x1test,y1test))
print("RFR Training Score:",rfr1.score(x1train,y1train), "Testing score:",rfr1.score(x1test,y1test))
print("XGB Training Score:",xgb1.score(x1train,y1train), "Testing score:",xgb1.score(x1test,y1test))
print("DT  Training Score:",dt1.score(x1train,y1train),  "Testing score:",dt1.score(x1test,y1test))
print("KNN Training Score:",knn1.score(x1train,y1train), "Testing score:",knn1.score(x1test,y1test))

In [ ]:
#PERFORMANCE EVALUATION
from sklearn.metrics import mean_squared_error,root_mean_squared_error,mean_absolute_error,r2_score

In [ ]:
#MEAN SQUARED ERROR
print("LR :",mean_squared_error(y1test,lr1_ypred))
print("RFR :",mean_squared_error(y1test,rfr1_ypred))
print("XGB :",mean_squared_error(y1test,xgb1_ypred))
print("DT :",mean_squared_error(y1test,dt1_ypred))
print("KNN :",mean_squared_error(y1test,knn1_ypred))

In [ ]:
#ROOT MEAN SQUARED ERROR
print("LR :",root_mean_squared_error(y1test,lr1_ypred))
print("RFR :",root_mean_squared_error(y1test,rfr1_ypred))
print("XGB :",root_mean_squared_error(y1test,xgb1_ypred))
print("DT :",root_mean_squared_error(y1test,dt1_ypred))
print("KNN :",root_mean_squared_error(y1test,knn1_ypred))

In [ ]:
#MEAN ABSOLUTE ERROR
print("LR :",mean_absolute_error(y1test,lr1_ypred))
print("RFR :",mean_absolute_error(y1test,rfr1_ypred))
print("XGB :",mean_absolute_error(y1test,xgb1_ypred))
print("DT :",mean_absolute_error(y1test,dt1_ypred))
print("KNN :",mean_absolute_error(y1test,knn1_ypred))

In [ ]:
#R2 SCORE
print("LR :",r2_score(y1test,lr1_ypred))
print("RFR :",r2_score(y1test,rfr1_ypred))
print("XGB :",r2_score(y1test,xgb1_ypred))
print("DT :",r2_score(y1test,dt1_ypred))
print("KNN :",r2_score(y1test,knn1_ypred))